---
title: "Measuring Diplomatic Appeals"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
#output: html_notebook
---
# Introduction
For many, modern diplomatic exchange simply reflects an interdependent world. Compared to the 19th-century institutions where leaders sent diplomats to “lie for his country,” today’s consulates and embassies are filled by officers who spend more time assisting overseas citizens, interviewing visa applicants, and collecting local intellegence. A character in a 1960 novel expresses such a view: 

> The Foreign Service has had its day - enjoyable while it lasted, no doubt, but over now. The privileged being of the future is the travel agent.
> *Don't Tell Alfred* (1960). 

While partially true, diplomatic representation is much more important than commonly perceived. When Obama decided to end the U.S.-Cuba antagonism, for instance, one key gesture was the reopening of the Embassy in Havana. Following India’s independence, it sent a special delegation to Europe that recommended establishing representation in Nordic states – which had neither commercial nor colonial ties with India – to learn their ways of diplomacy. In both cases, diplomatic representation reflects a country’s recognition of the “diplomatic appeal” of its partner. Through institutionalizing an official relationship, a country recognize that its partner is ideologically agreeable,
and that further exchange of commerce, people, and ideas will be beneficial to both the governments and the population.


If a measurement of diplomatic appeal can be built on diplomatic representation data, we can answer a number of interesting questions in world politics: 

* How is a ranking of authority different from one of military power or economic size? 

We can also test the relationship between authority and state behavior:

* Are countries with high diplomatic authority tend to be better conflict mediators, more reliable allies, and stronger guardians of international law? 

Given policy-makers’ interests in **soft power** and **public diplomacy**, it is surprising that political scientists rarely took advantage of the diplomatic representation data last two decades. 

In this proposal, I argue that one reason 


```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

# Literature Review

# Data on Diplomatic Exchange
http://correlatesofwar.org/data-sets/diplomatic-exchange

## COW Data (1817-2005)

# An IRT Approach to Diplomatic Appeals





















